namespace Huzurevi.Application.Features.Sakinler;

public record SakinListDto(
    int Id,
    string? KayitNo,
    string Ad,
    string Soyad,
    string TcKimlikNo,
    string? Telefon,
    string Durum,
    bool AktifMi,
    bool FotoVarMi,
    int? YatakId,
    string? YatakBilgisi);

public record SakinYerlesimDto(
    int YatakId,
    int OdaId,
    string OdaNumarasi,
    int Kat,
    string? Blok,
    string YatakNumarasi,
    DateTime? GirisTarihi);

public record SakinDetayDto(
    int Id,
    string? KayitNo,
    string Ad,
    string Soyad,
    string TcKimlikNo,
    string? Telefon,
    DateTime DogumTarihi,
    DateTime KabulTarihi,
    string Durum,
    bool AktifMi,
    string? Cinsiyet,
    string? DogumYeri,
    string? Uyruk,
    string? MedeniDurum,
    string? KanGrubu,
    string? Adres,
    string? AcilTelefon,
    string? Notlar,
    string? BabaAdi,
    string? AnaAdi,
    string? OgrenimDurumu,
    string? Meslek,
    string? EngelDurumu,
    string? NeredenGeldigi,
    string? OncekiYasamYeri,
    string? NufusKutukIli,
    string? UcretDurumu,
    decimal? AylikGelir,
    string? BasvuruDurumu,
    string? KayitTuru,
    string? AyrilisDurumu,
    DateTime? AyrilisTarihi,
    string? KabulNedeni,
    string? KabulSekli,
    string? SonOturduguAdres,
    string? KimGetirdi,
    bool FotoVarMi,
    SakinYerlesimDto? Yerlesim,
    List<YakinDto> Yakinlar,
    List<SakinSurecAdimiDto> Surec);

public record SakinSurecAdimiDto(string Kod, string Baslik, string Durum, string? Ozet, int? Sekme);

public record KabulMuayeneDto(
    int SakinId,
    string? KayitNo,
    string AdSoyad,
    string TcKimlikNo,
    DateTime KabulTarihi,
    string Durum,
    bool OlcumVarMi,
    bool GelisVarMi,
    bool KonusmaVarMi,
    bool IsitmeVarMi,
    bool GormeVarMi,
    int Tamamlanan,
    int Toplam);

public record SakinOlusturIstek(
    string Ad,
    string Soyad,
    string TcKimlikNo,
    string? Telefon,
    string? Durum,
    DateTime? DogumTarihi,
    DateTime? KabulTarihi);

public record SakinGuncelleIstek(
    string Ad,
    string Soyad,
    string? Telefon,
    DateTime? DogumTarihi,
    DateTime? KabulTarihi,
    string? Durum,
    string? Cinsiyet,
    string? DogumYeri,
    string? Uyruk,
    string? MedeniDurum,
    string? KanGrubu,
    string? Adres,
    string? AcilTelefon,
    string? Notlar,
    string? BabaAdi,
    string? AnaAdi,
    string? OgrenimDurumu,
    string? Meslek,
    string? EngelDurumu,
    string? NeredenGeldigi,
    string? OncekiYasamYeri,
    string? NufusKutukIli,
    string? UcretDurumu,
    decimal? AylikGelir,
    string? BasvuruDurumu,
    string? KayitTuru,
    string? AyrilisDurumu,
    DateTime? AyrilisTarihi,
    string? KabulNedeni,
    string? KabulSekli,
    string? SonOturduguAdres,
    string? KimGetirdi);

public record YakinDto(
    int Id,
    int SakinId,
    string Ad,
    string Soyad,
    string Yakinlik,
    string? Telefon,
    string? Eposta,
    string? Adres,
    string? Meslek,
    string? Aciklama,
    int Oncelik,
    bool AcilDurumKisisiMi);

public record YakinOlusturIstek(
    string Ad,
    string Soyad,
    string Yakinlik,
    string? Telefon,
    string? Eposta,
    string? Adres,
    string? Meslek,
    string? Aciklama,
    int Oncelik,
    bool AcilDurumKisisiMi);

public record YakinGuncelleIstek(
    string Ad,
    string Soyad,
    string Yakinlik,
    string? Telefon,
    string? Eposta,
    string? Adres,
    string? Meslek,
    string? Aciklama,
    int Oncelik,
    bool AcilDurumKisisiMi);
