namespace Huzurevi.Application.Features.Sakinler;

public record VasiDto(
    int Id,
    int SakinId,
    string Ad,
    string Soyad,
    string? TcKimlikNo,
    DateTime? DogumTarihi,
    string? Telefon,
    string? Eposta,
    string? Adres,
    string? Yakinlik,
    string? MahkemeAdi,
    string? KararNo,
    DateTime? KararTarihi,
    DateTime? BaslangicTarihi,
    DateTime? BitisTarihi,
    string? Kapsam,
    string VasiTuru,
    string? Sebep,
    string Durum,
    string? Aciklama);

public record VasiOlusturIstek(
    string Ad,
    string Soyad,
    string? TcKimlikNo,
    DateTime? DogumTarihi,
    string? Telefon,
    string? Eposta,
    string? Adres,
    string? Yakinlik,
    string? MahkemeAdi,
    string? KararNo,
    DateTime? KararTarihi,
    DateTime? BaslangicTarihi,
    DateTime? BitisTarihi,
    string? Kapsam,
    string? VasiTuru,
    string? Sebep,
    string? Durum,
    string? Aciklama);

public record VasiGuncelleIstek(
    string Ad,
    string Soyad,
    string? TcKimlikNo,
    DateTime? DogumTarihi,
    string? Telefon,
    string? Eposta,
    string? Adres,
    string? Yakinlik,
    string? MahkemeAdi,
    string? KararNo,
    DateTime? KararTarihi,
    DateTime? BaslangicTarihi,
    DateTime? BitisTarihi,
    string? Kapsam,
    string? VasiTuru,
    string? Sebep,
    string? Durum,
    string? Aciklama);
