// <auto-generated />
using System;
using Huzurevi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Huzurevi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20260910100103_YatakSakinIdEklendi")]
    partial class YatakSakinIdEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Huzurevi.Domain.Entities.Oda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Blok")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kapasite")
                        .HasColumnType("integer");

                    b.Property<int>("Kat")
                        .HasColumnType("integer");

                    b.Property<string>("OdaNumarasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Odalar");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Sakin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("KabulTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("YatakId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TcKimlikNo")
                        .IsUnique();

                    b.HasIndex("YatakId")
                        .IsUnique();

                    b.ToTable("Sakinler");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Yatak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DoluMu")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OdaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YatakNumarasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OdaId");

                    b.ToTable("Yataklar");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Sakin", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Yatak", "Yatak")
                        .WithOne("Sakin")
                        .HasForeignKey("Huzurevi.Domain.Entities.Sakin", "YatakId");

                    b.Navigation("Yatak");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Yatak", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Oda", "Oda")
                        .WithMany("Yataklar")
                        .HasForeignKey("OdaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oda");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Oda", b =>
                {
                    b.Navigation("Yataklar");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Yatak", b =>
                {
                    b.Navigation("Sakin");
                });
#pragma warning restore 612, 618
        }
    }
}
