// <auto-generated />
using System;
using Huzurevi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Huzurevi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20260910160313_ZiyaretTablosu")]
    partial class ZiyaretTablosu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Huzurevi.Domain.Entities.IlacTakip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Dozaj")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IlacAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notlar")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("SakinId")
                        .HasColumnType("integer");

                    b.Property<bool>("VerildiMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Zaman")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SakinId");

                    b.ToTable("IlacTakipleri", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<int>("BasarisizGirisSayisi")
                        .HasColumnType("integer");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Eposta")
                        .IsUnique();

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Oda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Blok")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Kapasite")
                        .HasColumnType("integer");

                    b.Property<int>("Kat")
                        .HasColumnType("integer");

                    b.Property<string>("OdaNumarasi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OdaTipi")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("OdaNumarasi")
                        .IsUnique()
                        .HasFilter("\"SilindiMi\" = FALSE");

                    b.ToTable("Odalar", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Sakin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcilTelefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Adres")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Cinsiyet")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DogumYeri")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("KabulTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("KanGrubu")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MedeniDurum")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<string>("Uyruk")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("YatakId")
                        .HasColumnType("integer");

                    b.Property<int?>("YatakId2")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TcKimlikNo")
                        .IsUnique();

                    b.HasIndex("YatakId2");

                    b.ToTable("Sakinler", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Yakin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AcilDurumKisisiMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Adres")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Eposta")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SakinId")
                        .HasColumnType("integer");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Yakinlik")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("SakinId");

                    b.ToTable("Yakinlar", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Yatak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DoluMu")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("OdaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("SakinId")
                        .HasColumnType("integer");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("YatakNumarasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OdaId");

                    b.HasIndex("SakinId")
                        .IsUnique();

                    b.ToTable("Yataklar", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Ziyaret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CikisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notlar")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SakinId")
                        .HasColumnType("integer");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TcKimlikNo")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Yakinlik")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ZiyaretciAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ZiyaretciSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CikisTarihi");

                    b.HasIndex("SakinId");

                    b.ToTable("Ziyaretler", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.IlacTakip", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Sakin", "Sakin")
                        .WithMany("IlacTakipleri")
                        .HasForeignKey("SakinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sakin");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Sakin", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Yatak", "Yatak")
                        .WithMany()
                        .HasForeignKey("YatakId2");

                    b.Navigation("Yatak");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Yakin", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Sakin", "Sakin")
                        .WithMany("Yakinlar")
                        .HasForeignKey("SakinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sakin");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Yatak", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Oda", "Oda")
                        .WithMany("Yataklar")
                        .HasForeignKey("OdaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Huzurevi.Domain.Entities.Sakin", "Sakin")
                        .WithOne()
                        .HasForeignKey("Huzurevi.Domain.Entities.Yatak", "SakinId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Oda");

                    b.Navigation("Sakin");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Ziyaret", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Sakin", "Sakin")
                        .WithMany("Ziyaretler")
                        .HasForeignKey("SakinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sakin");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Oda", b =>
                {
                    b.Navigation("Yataklar");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Sakin", b =>
                {
                    b.Navigation("IlacTakipleri");

                    b.Navigation("Yakinlar");

                    b.Navigation("Ziyaretler");
                });
#pragma warning restore 612, 618
        }
    }
}
