// <auto-generated />
using System;
using Huzurevi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Huzurevi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20260910200129_SakinYakinSurecSaglikKayit")]
    partial class SakinYakinSurecSaglikKayit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Huzurevi.Domain.Entities.IlacTakip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Dozaj")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IlacAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notlar")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("SakinId")
                        .HasColumnType("integer");

                    b.Property<bool>("VerildiMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Zaman")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SakinId");

                    b.ToTable("IlacTakipleri", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<int>("BasarisizGirisSayisi")
                        .HasColumnType("integer");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Eposta")
                        .IsUnique();

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Mirasci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Adres")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SakinId")
                        .HasColumnType("integer");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TcKimlikNo")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Yakinlik")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("SakinId");

                    b.ToTable("Mirascilar", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Oda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Blok")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Kapasite")
                        .HasColumnType("integer");

                    b.Property<int>("Kat")
                        .HasColumnType("integer");

                    b.Property<string>("OdaNumarasi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OdaTipi")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("OdaNumarasi")
                        .IsUnique()
                        .HasFilter("\"SilindiMi\" = FALSE");

                    b.ToTable("Odalar", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Sakin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcilTelefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Adres")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("AnaAdi")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("AylikGelir")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("AyrilisDurumu")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("AyrilisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("BabaAdi")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BasvuruDurumu")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Cinsiyet")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DogumYeri")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EngelDurumu")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("FotoYolu")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("KabulNedeni")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("KabulSekli")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("KabulTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("KanGrubu")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("KayitNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("KayitTuru")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("KimGetirdi")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("MedeniDurum")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Meslek")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NeredenGeldigi")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NufusKutukIli")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OgrenimDurumu")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OncekiYasamYeri")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SonOturduguAdres")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<string>("UcretDurumu")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Uyruk")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("YatakId")
                        .HasColumnType("integer");

                    b.Property<int?>("YatakId2")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KayitNo")
                        .IsUnique()
                        .HasFilter("\"SilindiMi\" = FALSE AND \"KayitNo\" IS NOT NULL");

                    b.HasIndex("TcKimlikNo")
                        .IsUnique();

                    b.HasIndex("YatakId2");

                    b.ToTable("Sakinler", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.SakinBelge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BelgeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("BelgeTuru")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<long>("Boyut")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GecerlilikTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Grup")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IcerikTipi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OrijinalAd")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SakinId")
                        .HasColumnType("integer");

                    b.Property<string>("SaklamaYolu")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SakinId");

                    b.ToTable("SakinBelgeleri", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.SakinEmanet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Adet")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Deger")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("EmanetTuru")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IslemTuru")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Saat")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("SakinId")
                        .HasColumnType("integer");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TeslimAlan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TeslimEden")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SakinId");

                    b.ToTable("SakinEmanetleri", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.SakinGelir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Deger")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("GelirTuru")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Periyot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SakinId")
                        .HasColumnType("integer");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SakinId");

                    b.ToTable("SakinGelirleri", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.SakinGunlukIzin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("CikisSaati")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("DonusSaati")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SakinId")
                        .HasColumnType("integer");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Yer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("SakinId");

                    b.ToTable("SakinGunlukIzinleri", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.SakinMal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Adet")
                        .HasColumnType("integer");

                    b.Property<string>("Adres")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Deger")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MalTuru")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SakinId")
                        .HasColumnType("integer");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SakinId");

                    b.ToTable("SakinMallari", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.SakinOlcum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("BoyCm")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("KanGrubu")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("KiloKg")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SakinId")
                        .HasColumnType("integer");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SakinId");

                    b.ToTable("SakinOlcumleri", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.SakinSaglikDegerlendirme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SakinId")
                        .HasColumnType("integer");

                    b.Property<string>("Seviye")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Taraf")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("YardimciAracMi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SakinId", "Tur");

                    b.ToTable("SakinSaglikDegerlendirmeleri", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.SakinSaglikKayit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AmeliyatTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("BaslangicTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Bolge")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Derece")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Doz")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("DurumTipi")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Hastane")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Komplikasyon")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("KontrolTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("KullanimSikligi")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("MarkaModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReaksiyonTipi")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ReceteNo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("ReceteliMi")
                        .HasColumnType("boolean");

                    b.Property<int>("SakinId")
                        .HasColumnType("integer");

                    b.Property<string>("SeriNo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Taraf")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TeminTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Teshis")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UygulamaYolu")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ZamanDilimleri")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ZamanlamaTipi")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("SakinId", "Tur");

                    b.ToTable("SakinSaglikKayitlari", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.SakinSosyalGuvence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BaslangicTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GuvenceTuru")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SakinId")
                        .HasColumnType("integer");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SakinId");

                    b.ToTable("SakinSosyalGuvenceleri", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.SakinYerlesim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Blok")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CikisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Kat")
                        .HasColumnType("integer");

                    b.Property<int?>("OdaId")
                        .HasColumnType("integer");

                    b.Property<string>("OdaNumarasi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SakinId")
                        .HasColumnType("integer");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("YatakId")
                        .HasColumnType("integer");

                    b.Property<string>("YatakNumarasi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OdaId");

                    b.HasIndex("YatakId");

                    b.HasIndex("SakinId", "CikisTarihi");

                    b.ToTable("SakinYerlesimleri", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Vasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Adres")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("BaslangicTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Eposta")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Kapsam")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("KararNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("KararTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MahkemeAdi")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SakinId")
                        .HasColumnType("integer");

                    b.Property<string>("Sebep")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TcKimlikNo")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VasiTuru")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Yakinlik")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("SakinId");

                    b.ToTable("Vasiler", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Yakin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("AcilDurumKisisiMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Adres")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Eposta")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Meslek")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Oncelik")
                        .HasColumnType("integer");

                    b.Property<int>("SakinId")
                        .HasColumnType("integer");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Yakinlik")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("SakinId");

                    b.ToTable("Yakinlar", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Yatak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DoluMu")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("OdaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("SakinId")
                        .HasColumnType("integer");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("YatakNumarasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OdaId");

                    b.HasIndex("SakinId")
                        .IsUnique();

                    b.ToTable("Yataklar", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Ziyaret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CikisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notlar")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SakinId")
                        .HasColumnType("integer");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TcKimlikNo")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Yakinlik")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ZiyaretciAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ZiyaretciSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CikisTarihi");

                    b.HasIndex("SakinId");

                    b.ToTable("Ziyaretler", (string)null);
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.IlacTakip", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Sakin", "Sakin")
                        .WithMany("IlacTakipleri")
                        .HasForeignKey("SakinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sakin");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Mirasci", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Sakin", "Sakin")
                        .WithMany("Mirascilar")
                        .HasForeignKey("SakinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sakin");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Sakin", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Yatak", "Yatak")
                        .WithMany()
                        .HasForeignKey("YatakId2");

                    b.Navigation("Yatak");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.SakinBelge", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Sakin", "Sakin")
                        .WithMany("Belgeler")
                        .HasForeignKey("SakinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sakin");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.SakinEmanet", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Sakin", "Sakin")
                        .WithMany("Emanetler")
                        .HasForeignKey("SakinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sakin");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.SakinGelir", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Sakin", "Sakin")
                        .WithMany("Gelirler")
                        .HasForeignKey("SakinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sakin");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.SakinGunlukIzin", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Sakin", "Sakin")
                        .WithMany("GunlukIzinler")
                        .HasForeignKey("SakinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sakin");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.SakinMal", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Sakin", "Sakin")
                        .WithMany("Mallar")
                        .HasForeignKey("SakinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sakin");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.SakinOlcum", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Sakin", "Sakin")
                        .WithMany("Olcumler")
                        .HasForeignKey("SakinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sakin");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.SakinSaglikDegerlendirme", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Sakin", "Sakin")
                        .WithMany("SaglikDegerlendirmeleri")
                        .HasForeignKey("SakinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sakin");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.SakinSaglikKayit", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Sakin", "Sakin")
                        .WithMany("SaglikKayitlari")
                        .HasForeignKey("SakinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sakin");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.SakinSosyalGuvence", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Sakin", "Sakin")
                        .WithMany("SosyalGuvenceler")
                        .HasForeignKey("SakinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sakin");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.SakinYerlesim", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Oda", "Oda")
                        .WithMany()
                        .HasForeignKey("OdaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Huzurevi.Domain.Entities.Sakin", "Sakin")
                        .WithMany("Yerlesimler")
                        .HasForeignKey("SakinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Huzurevi.Domain.Entities.Yatak", "Yatak")
                        .WithMany()
                        .HasForeignKey("YatakId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Oda");

                    b.Navigation("Sakin");

                    b.Navigation("Yatak");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Vasi", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Sakin", "Sakin")
                        .WithMany("Vasiler")
                        .HasForeignKey("SakinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sakin");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Yakin", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Sakin", "Sakin")
                        .WithMany("Yakinlar")
                        .HasForeignKey("SakinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sakin");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Yatak", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Oda", "Oda")
                        .WithMany("Yataklar")
                        .HasForeignKey("OdaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Huzurevi.Domain.Entities.Sakin", "Sakin")
                        .WithOne()
                        .HasForeignKey("Huzurevi.Domain.Entities.Yatak", "SakinId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Oda");

                    b.Navigation("Sakin");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Ziyaret", b =>
                {
                    b.HasOne("Huzurevi.Domain.Entities.Sakin", "Sakin")
                        .WithMany("Ziyaretler")
                        .HasForeignKey("SakinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sakin");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Oda", b =>
                {
                    b.Navigation("Yataklar");
                });

            modelBuilder.Entity("Huzurevi.Domain.Entities.Sakin", b =>
                {
                    b.Navigation("Belgeler");

                    b.Navigation("Emanetler");

                    b.Navigation("Gelirler");

                    b.Navigation("GunlukIzinler");

                    b.Navigation("IlacTakipleri");

                    b.Navigation("Mallar");

                    b.Navigation("Mirascilar");

                    b.Navigation("Olcumler");

                    b.Navigation("SaglikDegerlendirmeleri");

                    b.Navigation("SaglikKayitlari");

                    b.Navigation("SosyalGuvenceler");

                    b.Navigation("Vasiler");

                    b.Navigation("Yakinlar");

                    b.Navigation("Yerlesimler");

                    b.Navigation("Ziyaretler");
                });
#pragma warning restore 612, 618
        }
    }
}
